### ISSUE TITLE
Error: Critical CSS <style> element not found

### ISSUE THREAD

**Issue by Seek51** [o10n-x/critical-css-widget#1]
Here there,

I am always getting the error:
Error: Critical CSS <style> element not found
![error critical css style element not found](https://user-images.githubusercontent.com/25787892/37078142-56d9a78e-21de-11e8-9fc2-669de79138e5.JPG)

Why this could happen?

**Comment by optimalisatie** [comment]
Hi!

The message means most likely that no critical CSS has been added yet. The critical CSS editor has a lower priority since it does work correctly besides this small user experience issue. We will improve the editor soon.

To resolve the issue, it is required to add a critical CSS file.
