### ISSUE TITLE
Failed to read the 'cssRules' property from 'CSSStyleSheet':

### ISSUE THREAD

**Issue by albertopontalto** [o10n-x/critical-css-widget#2]
Hi. 
I am using Google Chrome 66.0.3359.181 (Build ) (a 64 bit)

When i paste this into google chrome dev console
`(function(d,c,s) {s=d.createElement('script');s.async=true;s.onload=c;s.src='https://cdn.rawgit.com/o10n-x/critical-css-widget/master/critical-css-widget.min.js';d.head.appendChild(s);})(document,function() {
   // critical css file download
   o10n.extract();
});`

It give me the following error  

![image](https://user-images.githubusercontent.com/28781042/40357571-e54cb136-5dbc-11e8-8adf-acdff1e12fd6.png)

Can you help me?

**Comment by optimalisatie** [comment]
Hi @albertopontalto,

Thank you very much for your feedback!

We have updated the widget with an improvement that should ignore the error.

https://github.com/o10n-x/critical-css-widget/releases/tag/1.0.2

The error is most likely related to external stylesheets.

The widget is based on a concept by Paul Kinlan, head of Chrome webdeveloper relations team. 

https://gist.github.com/PaulKinlan/6284142

The original snippet uses a Chrome innovation called `getMatchedCSSRules` which is deprecated and has been removed in Chrome 63. The Critical CSS Widget is made cross browser using a polyfill for `getMatchedCSSRules`. It appears that Chrome 66 ads a security error when trying to access `cssRules` for external stylesheets.

![image](https://user-images.githubusercontent.com/8843669/36543121-1da8cc7e-17e3-11e8-8ed1-a7f69b47757c.png)
